image: node:latest

stages:
  - deploy

deploy:
  only:
    - tags
  stage: deploy
  before_script:
    - yarn install --frozen-lockfile
  script:
    - yarn build
    - npm publish
  artifacts:
    paths:
      - dist
