image: node:latest

stages:
  - deploy

deploy:
  only:
    - tags
  stage: deploy
  before_script:
    - yarn install --frozen-lockfile
  script:
    - yarn build
    - npm run obfuscate
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
  artifacts:
    paths:
      - dist